---
- include: deps.yml

- include: lua.yml
  when: include_lua is defined

- include: openssl.yml

- include: pagespeed.yml
  when: include_pagespeed is defined

- include: upload_progress.yml
  when: include_upload_progress is defined

- include: nginx.yml
