---
- name: Get current openssl version
  shell: openssl version | awk '{ print $2 }'
  register: current_openssl_version

- name: Extract archives
  unarchive: 
    src: "{{ item }}"
    copy: no 
    dest: "{{ destination }}"
  with_items:
    - "{{ openssl_source_url }}"

- name: Openssl - compile
  become: true
  command: chdir="{{destination}}/{{openssl}}" {{ item }}
  with_items:
    - ./config
    - make depend
    - make

- name: Openssl - make test
  command: chdir="{{destination}}/{{openssl}}" make test

- name: Openssl - move openssl binary
  become: true
  command: "mv /usr/bin/openssl /usr/bin/openssl_{{ current_openssl_version.stdout}}" 

- name: Openssl - make install
  command: chdir="{{destination}}/{{openssl}}" make install
  become: true

- name: Openssl - move new library
  command: "mv {{ destination }}/{{ openssl }}/apps/openssl /usr/bin/openssl"
  become: true
