---
- name: systemd reload
  become: true
  command: "{{ item }}"
  with_items:
    - systemctl daemon-reload

- name: enable nginx
  become: true
  command: "{{ item }}"
  with_items:
    - systemctl enable nginx.service

- name: restart nginx
  become: true
  command: "{{ item }}"
  with_items:
    - systemctl restart nginx.service
